export const dummyPersonalResponses = [
    "Take a 5-minute walk outside and breathe deeply.",
    "Write down three things you’re grateful for today.",
    "Text or call a loved one just to say hello.",
    "Stretch for 10 minutes, focusing on your breathing.",
    "Enjoy a cup of tea or coffee in peace.",
    "Listen to your favorite song and dance around.",
    "Take a 5-minute break to simply close your eyes and relax.",
    "Write a letter to your future self.",
    "Make your bed to start your day with a sense of accomplishment.",
    "Do a kind deed for someone, even if it’s small.",
    "Try a new recipe or make a healthy snack.",
    "Read a chapter of a book or listen to an audiobook for 15 minutes.",
    "Watch the sunset or sunrise, and take a moment to appreciate it.",
    "Meditate for 5-10 minutes, focusing on your breath.",
    "Organize a small area in your home that feels cluttered.",
    "Plant a small flower or herb, or care for a plant.",
    "Take a break and watch a funny video or show to lift your mood.",
    "Write down your thoughts and feelings in a journal.",
    "Do a random act of kindness for a stranger.",
    "Go outside and spend time in nature, even for just 10 minutes.",
    "Try a breathing exercise to calm your mind and body.",
    "Take a 10-minute digital detox and disconnect from your devices.",
    "Do something creative: draw, paint, or craft something simple.",
    "Create a playlist of your favorite calming or uplifting songs.",
    "Have a moment of silence and focus on your senses.",
    "Make a list of personal goals, big or small, and celebrate one achievement.",
    "Take a relaxing bath with soothing scents or essential oils.",
    "Give yourself a compliment in the mirror.",
    "Spend time with a pet or animal for a calming connection.",
    "Take 5 minutes to simply breathe deeply and reset your mind."
];

export const dummyRewardsData = [
    {
        "id": 1,
        "title": "10% Off Your First Order",
        "description": "Enjoy 10% off your first purchase with us.",
        "code": "FIRST10",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 2,
        "title": "Free Shipping on Orders Over $50",
        "description": "Get free shipping on all orders over $50.",
        "code": "FREESHIP50",
        "image": "src/assets/rewardsImage2.jpg",
    },
    {
        "id": 3,
        "title": "Buy One Get One Free",
        "description": "Buy one item and get the second one free of equal or lesser value.",
        "code": "BOGOF",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 4,
        "title": "25% Off All Accessories",
        "description": "Take 25% off all accessories for a limited time.",
        "code": "ACCESSORY25",
        "image": "src/assets/rewardsImage2.jpg",
    },
    {
        "id": 5,
        "title": "Free Gift With Purchase",
        "description": "Get a free gift with any purchase over $100.",
        "code": "FREEGIFT100",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 6,
        "title": "Free Coffee for a Month",
        "description": "Get a free coffee every day for the next month when you sign up.",
        "code": "COFFEE30",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 7,
        "title": "50% Off Your Second Item",
        "description": "Get 50% off your second item when you buy one at full price.",
        "code": "SECOND50",
        "image": "src/assets/rewardsImage2.jpg",
    },
    {
        "id": 8,
        "title": "Free Movie Ticket",
        "description": "Get a free movie ticket with any purchase over $75.",
        "code": "MOVIEFREE",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 9,
        "title": "Spend $200, Get $50 Off",
        "description": "Spend $200 and get $50 off your next order.",
        "code": "SAVE50",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 10,
        "title": "Free Spa Day",
        "description": "Get a free spa day when you book a weekend getaway.",
        "code": "SPAFREE",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 11,
        "title": "Trip to Bali for Two",
        "description": "Win a free trip to Bali for two, including flights and accommodation.",
        "code": "BALI2025",
        "image": "src/assets/rewardsImage2.jpg",
    },
    {
        "id": 12,
        "title": "Free Trial for 30 Days",
        "description": "Try our premium service free for 30 days.",
        "code": "TRIAL30",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 13,
        "title": "Discounted Weekend Getaway",
        "description": "Book a weekend getaway and enjoy 30% off.",
        "code": "WEEKEND30",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 14,
        "title": "$100 Off Your Next Purchase",
        "description": "Save $100 off your next purchase of $500 or more.",
        "code": "SAVE100",
        "image": "src/assets/rewardsImage2.jpg",
    },
    {
        "id": 15,
        "title": "Free Concert Tickets",
        "description": "Get a pair of free concert tickets to your favorite band.",
        "code": "CONCERTFREE",
        "image": "src/assets/rewardsImage1.jpg",
    },
    {
        "id": 16,
        "title": "50% Off Your Stay",
        "description": "Enjoy 50% off your next hotel stay at select locations.",
        "code": "STAY50",
        "image": "src/assets/rewardsImage1.jpg",
    },
];

